---
- name: Pre-Checks for CI/CD Pipeline
  hosts: localhost
  gather_facts: no
  tasks:
   - name: Check if Git is installed
     shell: git --version
     register: git_installed
     ignore_errors: yes
 
   - name: Check if Maven is installed
     shell: mvn --version
     register: maven_version
     ignore_errors: yes
 
   - name: Check if SonarQube is reachable
     uri:
       url: http://10.138.77.104:9000
     register: sonarqube_status
     ignore_errors: yes
 
   - name: Check if Docker Registry is reachable
     uri:
       url: https://hub.docker.com/u/bhavanaguda
     register: docker_registry_status
     ignore_errors: yes
 
   - name: Check if Kubernetes is installed
     shell: kubectl version --client
     register: kubernetes_installed
     ignore_errors: yes
 
   - name: Display pre-checks status
     debug:
       msg: |
         Git: Installed: {{ 'Installed' if git_installed.rc == 0 else 'Not Installed' }}
         Maven: Installed: {{'Installed' if maven_version.rc == 0 else 'Not Installed' }}
         SonarQube: Reachable: {{'Reachable' if sonarqube_status.status == 200 else 'Not Reachable'}}
         Docker Registry: {{'Installed' if docker_registry_status.status == 200 else 'Not Installed' }}
         Kubernetes: {{'Installed' if kubernetes_installed.rc == 0 else 'Not Installed'}}
